### ISSUE TITLE
Fix downstairs toilet

### ISSUE THREAD

**Issue by hdean0212** [jhkennedy/home#1]
Downstairs toilet wobbles when you sit on it and likely doesn't have a good seal.

**Comment by jhkennedy** [comment]
Toilet flange is broken. Because it's a glued in PCV flange, I believe this is a job for a professional. 

Since, we'll need to bring in someone, may as well look into #4 at the same time.

**Comment by jhkennedy** [comment]
Going to hold off on #4 and get a flange repair ring to fix toilet. When we do #4, we'll have it fixed for real.

**Comment by jhkennedy** [comment]
Flange repair ring won't work with the slab foundation; need plumber. Sigh.

**Comment by jhkennedy** [comment]
Plumber coming tomorrow evening to check it out.

**Comment by jhkennedy** [comment]
Fixed! $257.00 later... :-(
