### ISSUE TITLE
Tile laundry and downstairs bath

### ISSUE THREAD

**Issue by jhkennedy** [jhkennedy/home#4]
The linolium in the laundry and downstairs bath is awful. A nice gray to dark gray tile would match nicely.

**Comment by jhkennedy** [comment]
because #1 is bigger than expected, we're looking into a quote.

**Comment by jhkennedy** [comment]
Our tile installation estimate is in: [CustomerReport.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5926f6d61a8cfc001adaa035/125516c66e82c728ace21e0d46cb8189378d8eac9ddbba53ab4fe4d665043761260ea62864c7b96aea1b2e570b0b4cfe130a5716f9ac892ba4e534778e5858b8c3714d36976345f3e5db55ea43a82a994c84bcbd8e45c9ef3426e68a8e473d1c1755.pdf)

Cost of Labor to:
* Remove & haul old vinyl flooring (because slab foundation)
* Install tile
* reinstall shoe molding
* install flooring transition

is **$887.68** (before materials). 

So, with materials, and plumber, it would cost ~ $1400.00 or two month of both of our hobby monies.

**Comment by jhkennedy** [comment]
Shelving this for now -- don't want to spend the money yet.

**Comment by hdean0212** [comment]
I agree, let's deal with the mouse issue first. We can tile later this winter. In the mean time let's just get that downstairs toilet fixed so that we have a working half bath.

**Comment by jhkennedy** [comment]
#1 is fixed -- we had a plumber come out to deal with it. But, when we do this, we'll need to have the sink raised for the new floor height, so we should have the plumber fix #25

**Comment by jhkennedy** [comment]
Bathroom has been tiled, but the sink has not been raised yet. Making a new issue for that.
