### ISSUE TITLE
Sticky timer in guest bath

### ISSUE THREAD

**Issue by jhkennedy** [jhkennedy/home#6]
The fan timer in the quest bath is sticking on sometimes. 

Need to:
- [ ] buy new timer at lowes (Home Depot doesn't seem to have the same kind)
- [ ] replace timer

**Comment by jhkennedy** [comment]
@hdean0212 , has it still been sticking? I haven't noticed it in a while.

**Comment by hdean0212** [comment]
I haven't noticed it either.

**Comment by jhkennedy** [comment]
Awesome, closing this issue. If you notice again, re-open it.

**Comment by hdean0212** [comment]
And it's back. Fan ran all day today.

**Comment by jhkennedy** [comment]
Replaced the timer. Should be fixed now.
